# Generated by Django 5.0.7 on 2024-07-24 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FavoriteURL', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite_url',
            name='status',
            field=models.TextField(choices=[('valid ', 'valid '), ('invalid ', 'invalid ')], default='valid'),
        ),
        migrations.CreateModel(
            name='CheckUrlsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datecheck', models.DateField()),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['-id'], name='FavoriteURL_id_50a30a_idx')],
            },
        ),
    ]
