# Generated by Django 5.0.7 on 2024-07-24 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FavoriteURL', '0002_favorite_url_status_checkurlslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type_name',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='tage_name',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
